### ISSUE TITLE
Invalid Strata object

### ISSUE THREAD

**Issue by champ52018** [arendsee/phylostratr#10]
tid<-'47426'
strata=uniprot_strata(tid, from = 2) %>% strata_apply(f= diverse_subtree,n=5,weights=uniprot_weight_by_ref()) %>% use_recommended_prokaryotes() %>% add_taxa(c('4932', '9606')) %>% uniprot_fill_strata()

#it shows the following error
Error in is_valid_strata(strata) : 
  Invalid Strata object, the focal species '47426' is not found in the tree

May I know what might be the issue? I checked the organism 'A.cepistipes'; it exist in NCBI taxonomy but, the program could not  identify it. Please help me solve the issue.

Any help would be appreciated! Thanks

**Comment by arendsee** [comment]
@champ52018 Thanks for the reproducible report! The problem here is that _Armillaria cepistipes_ is not in the UniProt database. This is a real bug though, since `phylostratr` should give you a chance to add your own sequence before blowing up. Pull the latest version of `phylostratr` from github and the problem should be fixed. You will still have to provide your own proteome for the focal species. See the code below:

``` R
require('phylostratr')
tid<-'47426'
strata=uniprot_strata(tid, from = 5) %>% 
  strata_apply(f=diverse_subtree,n=2,weights=uniprot_weight_by_ref()) %>% 
  use_recommended_prokaryotes() %>%
  add_taxa(c('4932', '9606')) %>%
  uniprot_fill_strata()
strata@data$faa[[tid]] <- '/path/to/your/file.faa'
```
Let me know if this works for you.

**Comment by champ52018** [comment]
@arendsee  Thank you so much for your reply! I tried again using the latest version of pylostratr (BMC Release (https://github.com/arendsee/phylostratr/releases/tag/0.2.0) but I got the same error. It blows up again. 

I am copying the steps I followed so that I can explain better:

1. I removed the previous version that I installed from github.
2. I downloaded the source code: https://github.com/arendsee/phylostratr/archive/0.2.0.tar.gz and installed it using  
> install.packages("phylostratr_v_0.2.0_bmc_release.tar.gz", repos=NULL)
3. I tried to rerun the previous analysis but it showed the same error
> tid<-'47426'
> strata=uniprot_strata(tid, from = 5) %>% 
  strata_apply(f=diverse_subtree,n=2,weights=uniprot_weight_by_ref()) %>% 
  use_recommended_prokaryotes() %>%
  add_taxa(c('4932', '9606')) %>%
  uniprot_fill_strata()

Error in is_valid_strata(strata) : 
  Invalid Strata object, the focal species '47426' is not found in the tree

Any help would be highly appreciated!

Thanks again!

**Comment by arendsee** [comment]
Ah, you are downloading the last tagged release, not the most recent one. Try installing like so:

``` R
devtools::install_github("arendsee/phylostratr")
```

That will retrieve the very latest version.

**Comment by champ52018** [comment]
Hi, at first I downloaded and installed using: 
> devtools::install_github("arendsee/phylostratr")

The second time, after seeing your message I did using 
> install.packages("phylostratr_v_0.2.0_bmc_release.tar.gz", repos=NULL)

**Comment by arendsee** [comment]
The command

``` R
install.packages("phylostratr_v_0.2.0_bmc_release.tar.gz", repos=NULL)
```

installs the old version, you should use the version I just committed to github. You can get that through `devtools::install_github`.

**Comment by champ52018** [comment]
Hi I did that as well. It gives the same problem.

**Comment by arendsee** [comment]
Can you show me the output of `devtools::session_info()`?

**Comment by arendsee** [comment]
@champ52018 Did you find a solution to the problem?

**Comment by wolfylair** [comment]
Hi, I encountered the same problem when running the same code as @champ52018 did. I checked the strata object and found that the function 'is_valid_strata' casts the error as there is no focal species taxa id found in strata@tree$tip.label. I installed your latest version of Phylostratr via devtools::github() but the issues persists. 

So I made a DIY solution by manually adding focal species taxa id at the end of the strata@tree$tip.label, and problem solved! 

I am not sure what i did might affect the tree structure, will such manipulation on tip.label make the results different from what it should be?
